# Generated by Django 5.1.2 on 2024-11-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
